import type { AdapterMatchResult, DomLocator, JobPageAdapter, PageContext, WebJobCapture } from '@job-compliance/shared';
export interface JobAdapterConfig { id: string; version: string; displayName: string; domains: string[]; pageMatchers: Array<{ urlPattern?: string; requiredTexts?: string[] }>; fields: Partial<Record<keyof WebJobCapture['job'], Array<{ type: 'LABEL_VALUE' | 'SECTION_TEXT'; labels?: string[]; headings?: string[] }>>>; }
/** Applies only reviewer-provided configuration to already captured text; no site credentials or page actions. */
export class ConfigurableJobPageAdapter implements JobPageAdapter {
  readonly id; readonly version; readonly supportedDomains;
  constructor(private readonly config: JobAdapterConfig) { this.id = config.id; this.version = config.version; this.supportedDomains = config.domains; }
  supports(context: PageContext): AdapterMatchResult { const matched = this.config.pageMatchers.some((item) => (!item.urlPattern || new RegExp(item.urlPattern).test(context.url)) && (item.requiredTexts ?? []).every((text) => context.mainText.includes(text))); return { supported: matched, confidence: matched ? .8 : 0, pageType: matched ? 'JOB_DETAIL' : 'UNKNOWN' }; }
  async extract(context: PageContext): Promise<WebJobCapture> { const value = (rules: typeof this.config.fields[keyof WebJobCapture['job']]) => rules?.flatMap((rule) => (rule.labels ?? rule.headings ?? []).map((label) => { const match = context.mainText.match(new RegExp(`${label}[：:]?\\s*([^\\n]{1,500})`, 'u')); return match?.[1]?.trim(); })).find(Boolean); const field = (rules: typeof this.config.fields[keyof WebJobCapture['job']]) => { const text = value(rules); return text ? { value: text, confidence: .8, source: 'SITE_ADAPTER' as const, locator: { textQuote: text } } : undefined; }; const title = field(this.config.fields.title); const description = field(this.config.fields.description); return { captureId: crypto.randomUUID(), sourceType: 'BROWSER_EXTENSION', pageUrl: context.url, pageTitle: context.title, capturedAt: new Date().toISOString(), adapter: { id: this.id, version: this.version, confidence: .8 }, job: { ...(title ? { title } : {}), ...(description ? { description } : {}) }, rawContent: { mainText: context.mainText }, completenessScore: title && description ? .22 : .11, extractionWarnings: [] }; }
  locateField(_field: keyof WebJobCapture['job'], _context: PageContext): DomLocator | null { return null; }
}
