import type { FastifyInstance } from 'fastify'; import { z } from 'zod';
import type { AuditJobHandler } from '../audit/routes.js'; import { InMemoryAuditRunStore, type AuditRunStore } from '../audit/store.js'; import { ExtensionAuthError, ExtensionAuthService } from '../extension-auth/service.js'; import { InMemoryWebCaptureStore } from './store.js';
const captureSchema = z.object({ sourceType: z.enum(['BROWSER_EXTENSION', 'PUBLIC_URL']), pageUrl: z.string().url(), pageTitle: z.string().max(500), adapter: z.object({ id: z.string(), version: z.string(), confidence: z.number().min(0).max(1) }), job: z.record(z.string(), z.unknown()), rawContent: z.object({ mainText: z.string().max(100_000), structuredData: z.unknown().optional() }), completenessScore: z.number().min(0).max(1), extractionWarnings: z.array(z.string().max(500)).max(100) });
const bearer = (value: unknown) => typeof value === 'string' && value.startsWith('Bearer ') ? value.slice(7) : undefined;
const context = (service: ExtensionAuthService, authorization: unknown, scope: Parameters<ExtensionAuthService['authenticate']>[1]) => { const token = bearer(authorization); if (!token) throw new ExtensionAuthError('EXTENSION_NOT_AUTHENTICATED'); return service.authenticate(token, scope); };
export function registerWebCaptureRoutes(app: FastifyInstance, dependencies: { auth: ExtensionAuthService; store: InMemoryWebCaptureStore; auditStore: AuditRunStore; auditJob: AuditJobHandler }): void {
  app.post('/api/web-captures', async (request, reply) => { const token = context(dependencies.auth, request.headers.authorization, 'web_capture:create'); const body = captureSchema.parse(request.body); const capture = dependencies.store.create({ ...body, captureId: '', capturedAt: new Date().toISOString() }, { tenantId: token.context.tenantId ?? 'default', userId: token.context.userId }); return reply.code(201).send(capture); });
  app.get('/api/web-captures/:id', async (request, reply) => { const token = context(dependencies.auth, request.headers.authorization, 'web_capture:read'); const id = z.object({ id: z.string() }).parse(request.params).id; const capture = dependencies.store.get(id, token.context.tenantId ?? 'default'); return capture ? reply.send(capture) : reply.code(404).send({ error: { code: 'CAPTURE_NOT_FOUND' } }); });
  app.post('/api/web-captures/:id/audit', async (request, reply) => { const token = context(dependencies.auth, request.headers.authorization, 'audit:create'); const id = z.object({ id: z.string() }).parse(request.params).id; const tenantId = token.context.tenantId ?? 'default'; const capture = dependencies.store.get(id, tenantId); if (!capture) return reply.code(404).send({ error: { code: 'CAPTURE_NOT_FOUND' } }); const title = capture.job.title?.value ?? capture.pageTitle; const description = capture.job.description?.value ?? capture.rawContent.mainText; if (!title || !description) return reply.code(422).send({ error: { code: 'CAPTURE_VALIDATION_FAILED' } }); const auditRequest = { tenantId, jobPostingId: capture.captureId, company: { name: capture.job.companyName?.value ?? 'Unknown' }, job: { title, description, ...(capture.job.location ? { location: capture.job.location.value } : {}), ...(capture.job.salary ? { salary: capture.job.salary.value } : {}) }, options: { jurisdiction: 'CN_MAINLAND' as const, enableRewrite: false, enableRag: false } }; const result = await dependencies.auditJob({ title, description, externalId: capture.captureId, companyName: auditRequest.company.name }, auditRequest); await dependencies.auditStore.save(result, { tenantId, jobPosting: { title, description, externalId: capture.captureId, companyName: auditRequest.company.name } }); dependencies.store.markAudited(id, tenantId, result.auditId); return reply.code(201).send(result); });
}
