import { PostgresLLMPersistenceRepository, type AsyncJobEntity } from '@job-compliance/database';

export const enrichmentTypes = ['AUDIT_GENERATE_EXPLANATIONS', 'AUDIT_GENERATE_REWRITE'] as const;
export type EnrichmentType = (typeof enrichmentTypes)[number];
export interface EnrichmentJobPayload { tenantId:string; auditRunId:string; jobType:EnrichmentType; promptVersion:string; modelVersion?:string; connectionId?:string; idempotencyKey:string; }
export interface EnrichmentRepository { releaseExpiredLocks():Promise<number>; claimNext(workerId:string,types:string[],lockDurationMs:number):Promise<AsyncJobEntity|null>; completeJob(id:string,result:unknown):Promise<void>; retryJob(id:string,errorCode:string,availableAt:Date):Promise<void>; deadLetter(id:string,errorCode:string):Promise<void>; createUsage(input: {tenantId:string;auditRunId?:string;asyncJobId?:string;provider:string;model:string;taskType?:string;promptVersion?:string;durationMs?:number;success?:boolean;errorCode?:string;isMock:boolean}):Promise<unknown>; }

/** Deterministic provider used unless a separately configured provider is injected. */
export class MockEnrichmentProvider { async generate(type:EnrichmentType, payload:EnrichmentJobPayload):Promise<Record<string,unknown>> { return type === 'AUDIT_GENERATE_EXPLANATIONS' ? { kind:'EXPLANATION', auditRunId:payload.auditRunId, summary:'该结果由规则与可追溯证据生成，建议结合人工复核流程处理。', isMock:true } : { kind:'REWRITE', auditRunId:payload.auditRunId, rewrittenText:'请使用中性、明确且不包含收费或敏感个人信息要求的招聘表述。', secondaryRuleCheck:'REVIEW', isMock:true }; } }
export class EnrichmentWorker {
  constructor(private readonly repository:EnrichmentRepository, private readonly provider=new MockEnrichmentProvider(), private readonly workerId=process.env.WORKER_ID ?? `enrichment-${process.pid}`) {}
  async runOnce():Promise<boolean>{ await this.repository.releaseExpiredLocks(); const job=await this.repository.claimNext(this.workerId,[...enrichmentTypes],30_000); if(!job)return false; const started=Date.now(); const payload=job.payload as unknown as EnrichmentJobPayload; const usageBase={tenantId:job.tenantId,...(job.auditRunId===undefined?{}:{auditRunId:job.auditRunId}),asyncJobId:job.id,provider:'MOCK',model:'mock-enrichment-v1',taskType:job.type,promptVersion:payload.promptVersion,durationMs:Date.now()-started,isMock:true}; try { if(!enrichmentTypes.includes(job.type as EnrichmentType) || payload.tenantId!==job.tenantId) throw new Error('INVALID_ENRICHMENT_PAYLOAD'); const result=await this.provider.generate(job.type as EnrichmentType,payload); await this.repository.completeJob(job.id,result); await this.repository.createUsage({...usageBase,success:true}); return true; } catch(error) { const code=error instanceof Error && error.message === 'INVALID_ENRICHMENT_PAYLOAD' ? 'INVALID_ENRICHMENT_PAYLOAD' : 'ENRICHMENT_PROVIDER_FAILED'; if(job.attemptCount >= job.maxAttempts) await this.repository.deadLetter(job.id,code); else await this.repository.retryJob(job.id,code,new Date(Date.now()+Math.min(60_000,1000*2**job.attemptCount))); await this.repository.createUsage({...usageBase,success:false,errorCode:code}); return true; } }
}

async function main():Promise<void>{ const repository=new PostgresLLMPersistenceRepository(); const worker=new EnrichmentWorker(repository); const once=process.argv.includes('--once'); let stopping=false; process.on('SIGINT',()=>{stopping=true;}); process.on('SIGTERM',()=>{stopping=true;}); do { const worked=await worker.runOnce(); if(once || !worked) { if(!once) await new Promise(resolve=>setTimeout(resolve,1000)); } } while(!once && !stopping); await repository.close(); }
if (process.argv[1]?.includes('enrichment-worker')) void main();
