'use client';

import { useEffect, useState } from 'react';
type Connection = { id: string; displayName: string; provider: string; auditModel: string; status: string; isDefault: boolean; apiKeyMasked?: string; lastVerifiedAt?: string };
export default function SettingsPage() {
  const [tenantId, setTenantId] = useState('tenant_web'); const [items, setItems] = useState<Connection[]>([]); const [error, setError] = useState<string>(); const [loading,setLoading]=useState(false);
  const load = async () => { setLoading(true);setError(undefined); const response = await fetch(`/api/settings/llm-connections?tenantId=${encodeURIComponent(tenantId)}`); setLoading(false); if (!response.ok) { setError('无法读取模型配置。'); return; } setItems((await response.json() as {items: Connection[]}).items); };
  const action=async(id:string,name:'verify'|'set-default'|'disable')=>{setError(undefined);const response=await fetch(`/api/settings/llm-connections/${id}/${name}?tenantId=${encodeURIComponent(tenantId)}`,{method:'POST'});if(!response.ok){setError(name==='verify'?'连接验证未通过；请检查密钥、模型或网络。':'操作未完成。');return;}await load();};
  useEffect(() => { void load(); }, []);
  return <main className="workspace"><section className="audit-form"><p className="section-label">AI Models / 模型配置</p><h1>租户模型连接</h1><p>密钥只在提交时发送，列表仅展示掩码；绿色状态仅代表真实探测已通过。</p><label><span>租户 ID</span><input value={tenantId} onChange={(event) => setTenantId(event.target.value)} /></label><button className="submit-button" disabled={loading} onClick={() => void load()}>{loading?'加载中…':'刷新状态'}</button>{error ? <p className="error-message">{error}</p> : null}<div className="finding-list">{!loading&&items.length === 0 ? <p className="empty-state">尚未配置模型连接。</p> : items.map((item) => <article className="finding-card" key={item.id}><h3>{item.displayName}</h3><p>{item.provider} · {item.auditModel} · {item.apiKeyMasked ?? '密钥已安全保存'}</p><p>状态：{item.status}{item.isDefault ? ' · 默认' : ''}</p><p>最近验证：{item.lastVerifiedAt ?? '尚未验证'}</p><p><button onClick={()=>void action(item.id,'verify')}>验证连接</button> <button disabled={item.status!=='ACTIVE'||item.isDefault} onClick={()=>void action(item.id,'set-default')}>设为默认</button> <button disabled={item.status==='DISABLED'} onClick={()=>void action(item.id,'disable')}>禁用</button></p></article>)}</div></section><aside className="review-note"><span>运营说明 / Operations</span><p>确定性规则优先；模型不可用时核心审核按策略降级。Usage、Trace 与队列状态仅由服务端持久化数据驱动。</p><a className="text-link" href={`/api/settings/llm-routing?tenantId=${encodeURIComponent(tenantId)}`}>查看当前路由策略</a></aside></main>;
}
