import { isUsableEvidence } from './finding-highlight-model.js';
import type { FindingHighlight } from './types.js';

const attribute = 'data-job-compliance-highlight';
const excludedTags = new Set(['SCRIPT', 'STYLE', 'NOSCRIPT', 'TEMPLATE', 'IFRAME', 'CANVAS', 'SVG', 'INPUT', 'TEXTAREA', 'SELECT', 'OPTION', 'BUTTON']);
interface IndexedTextNode { node: Text; start: number; end: number; }
interface NormalizedText { value: string; starts: number[]; ends: number[]; }
export interface HighlightStats { highlightedFindings:number; unlocatedFindings:number; matchedTextCount:number; }

export function normalizeEvidence(value: string): string { return normalizeWithOffsets(value).value; }
export function findEvidenceOffsets(pageText: string, evidence: string): Array<{ start:number; end:number }> {
  const normalizedPage = normalizeWithOffsets(pageText); const needle = normalizeEvidence(evidence); if (!isUsableEvidence(needle)) return [];
  const matches: Array<{ start:number; end:number }> = [];
  for (let index = normalizedPage.value.indexOf(needle); index !== -1; index = normalizedPage.value.indexOf(needle, index + needle.length)) matches.push({ start: normalizedPage.starts[index]!, end: normalizedPage.ends[index + needle.length - 1]! });
  return matches;
}
export function applyFindingHighlights(page: Document, findings: readonly FindingHighlight[]): HighlightStats {
  clearFindingHighlights(page); const indexed = indexVisibleText(page); const normalized = normalizeWithOffsets(indexed.text); const intervals: Array<{ start:number; end:number; ids:Set<string>; severity:FindingHighlight['severity'] }> = []; let highlightedFindings = 0; let unlocatedFindings = 0; let matchedTextCount = 0;
  for (const finding of findings) { const needle = normalizeEvidence(finding.text); if (!isUsableEvidence(needle)) { unlocatedFindings += 1; continue; } let count = 0; for (let index = normalized.value.indexOf(needle); index !== -1; index = normalized.value.indexOf(needle, index + needle.length)) { intervals.push({ start: normalized.starts[index]!, end: normalized.ends[index + needle.length - 1]!, ids:new Set([finding.id]), severity:finding.severity }); count += 1; } if (count === 0) unlocatedFindings += 1; else { highlightedFindings += 1; matchedTextCount += count; } }
  for (const interval of mergeIntervals(intervals).sort((left, right) => right.start - left.start)) wrapInterval(indexed.nodes, interval);
  return { highlightedFindings, unlocatedFindings, matchedTextCount };
}
export function clearFindingHighlights(page: Document): number { const highlights = Array.from(page.querySelectorAll(`span[${attribute}="true"]`)); for (const highlight of highlights) { const parent = highlight.parentNode; highlight.replaceWith(...Array.from(highlight.childNodes)); parent?.normalize(); } return highlights.length; }
function indexVisibleText(page: Document): { text:string; nodes:IndexedTextNode[] } { const nodes: IndexedTextNode[] = []; let text = ''; const walker = page.createTreeWalker(page.body ?? page.documentElement, NodeFilter.SHOW_TEXT, { acceptNode(node) { if (node.nodeValue === null || node.nodeValue.length === 0) return NodeFilter.FILTER_REJECT; const parent = node.parentElement; if (!parent || excludedTags.has(parent.tagName) || parent.closest(`[${attribute}]`) || parent.closest('[contenteditable="true"], [contenteditable=""]') || !isVisible(parent)) return NodeFilter.FILTER_REJECT; return NodeFilter.FILTER_ACCEPT; } }); for (let node = walker.nextNode(); node !== null; node = walker.nextNode()) { const textNode = node as Text; const start = text.length; text += textNode.data; nodes.push({ node:textNode, start, end:text.length }); } return { text, nodes }; }
function isVisible(element: Element): boolean { for (let current: Element | null = element; current !== null; current = current.parentElement) { if (current.hasAttribute('hidden') || current.getAttribute('aria-hidden') === 'true') return false; const view = current.ownerDocument.defaultView; if (view) { const style = view.getComputedStyle(current); if (style.display === 'none' || style.visibility === 'hidden' || style.visibility === 'collapse') return false; } } return true; }
function normalizeWithOffsets(value: string): NormalizedText { let normalized = ''; const starts: number[] = []; const ends: number[] = []; let whitespace = false; for (let index = 0; index < value.length; index += 1) { const char = value[index]!; if (/\s/u.test(char)) { if (!whitespace && normalized.length > 0) { normalized += ' '; starts.push(index); ends.push(index + 1); } whitespace = true; continue; } whitespace = false; normalized += /[A-Z]/u.test(char) ? char.toLowerCase() : char; starts.push(index); ends.push(index + 1); } if (normalized.endsWith(' ')) { normalized = normalized.slice(0, -1); starts.pop(); ends.pop(); } return { value:normalized, starts, ends }; }
function mergeIntervals(values: Array<{ start:number; end:number; ids:Set<string>; severity:FindingHighlight['severity'] }>) { const sorted = [...values].sort((left, right) => left.start - right.start || right.end - left.end); const merged: typeof sorted = []; for (const value of sorted) { const previous = merged.at(-1); if (previous && value.start < previous.end) { previous.end = Math.max(previous.end, value.end); value.ids.forEach((id) => previous.ids.add(id)); if (value.severity === 'CRITICAL' || value.severity === 'HIGH') previous.severity = value.severity; } else merged.push({ ...value, ids:new Set(value.ids) }); } return merged; }
function wrapInterval(nodes: readonly IndexedTextNode[], interval: { start:number; end:number; ids:Set<string>; severity:FindingHighlight['severity'] }): void { for (const indexed of [...nodes].reverse()) { if (indexed.end <= interval.start || indexed.start >= interval.end || !indexed.node.isConnected) continue; const start = Math.max(0, interval.start - indexed.start); const end = Math.min(indexed.node.data.length, interval.end - indexed.start); if (start < end) wrapText(indexed.node, start, end, interval); } }
function wrapText(node: Text, start: number, end: number, interval: { ids:Set<string>; severity:FindingHighlight['severity'] }): void { if (end < node.data.length) node.splitText(end); const target = start === 0 ? node : node.splitText(start); const wrapper = node.ownerDocument.createElement('span'); wrapper.setAttribute(attribute, 'true'); wrapper.dataset.jobComplianceFindingIds = [...interval.ids].sort().join(','); wrapper.dataset.jobComplianceSeverity = interval.severity; target.parentNode?.replaceChild(wrapper, target); wrapper.append(target); }
