import { submitAudit } from './api-client.js';
import { findingHighlights } from './finding-highlight-model.js';
import { createPageBinding } from './page-identity.js';
import { acceptsAuditResponse, invalidationReason } from './page-lifecycle.js';
import { invalidateState, loadConfig, loadState, saveConfig, saveState } from './storage.js';
import type { AuditResult, PageBinding, PageLifecycle, WebJobCapture } from './types.js';
import { isCapture, isPageIdentity } from './types.js';
import { selectSourceTab } from './source-tab.js';

const byId = <T extends HTMLElement>(id: string) => document.getElementById(id) as T;
const status = byId<HTMLElement>('status'); const preview = byId<HTMLElement>('preview'); const result = byId<HTMLElement>('result'); const submit = byId<HTMLButtonElement>('submit'); const highlight = byId<HTMLButtonElement>('highlight'); const clearHighlights = byId<HTMLButtonElement>('clearHighlights');
let capture: WebJobCapture | undefined; let auditResult: AuditResult | undefined; let binding: PageBinding | undefined; let lifecycle: PageLifecycle = { status: 'CURRENT' }; let sending = false; let highlighting = false; let clearing = false;
const fields = ['title', 'companyName', 'location', 'salary', 'employmentType', 'description', 'requirements'] as const;
function setStatus(value: string) { status.textContent = value; }
function current(): boolean { return lifecycle.status === 'CURRENT'; }
function showCapture(value: WebJobCapture) { capture = value; preview.hidden = false; submit.disabled = !current(); for (const field of fields) { const control = document.querySelector(`[data-field="${field}"]`) as HTMLInputElement | HTMLTextAreaElement | null; if (control) control.value = field === 'requirements' ? value.job.requirements.join('\n') : (value.job[field as keyof typeof value.job] as string | undefined ?? ''); } byId<HTMLElement>('warnings').textContent = value.extractionWarnings.join('\n'); }
function updatedCapture(): WebJobCapture | undefined { if (!capture || !current()) return undefined; const job = { ...capture.job }; for (const field of fields) { const control = document.querySelector(`[data-field="${field}"]`) as HTMLInputElement | HTMLTextAreaElement | null; const value = control?.value.trim() ?? ''; if (field === 'requirements') job.requirements = value ? value.split('\n').map((x) => x.trim()).filter(Boolean) : []; else if (field === 'title' || field === 'description') job[field] = value; else if (value) job[field as keyof typeof job] = value as never; else delete job[field as keyof typeof job]; } return { ...capture, job, userCorrected: true }; }
function showResult(value: AuditResult) { auditResult = value; result.hidden = false; highlight.disabled = !current() || findingHighlights(value).length === 0; clearHighlights.disabled = !current(); byId<HTMLElement>('decision').textContent = `${value.decision} · ${value.riskLevel}`; byId<HTMLElement>('summary').textContent = value.summary; byId<HTMLElement>('auditId').textContent = `AuditRun: ${value.auditId} · ${value.createdAt}`; const list = byId<HTMLUListElement>('findings'); list.replaceChildren(); for (const finding of value.findings) { const item = document.createElement('li'); const matched = (finding.metadata?.matchedText?.join('、') ?? finding.evidence.flatMap((e) => e.quote ? [e.quote] : []).join('、')) || '未提供原文'; item.textContent = `[${finding.severity}] ${finding.category}：${matched}。${finding.message}`; list.append(item); } }
function showStale(): void { lifecycle = lifecycle.status === 'STALE' ? lifecycle : { status: 'STALE', reason: 'PAGE_BINDING_CHANGED', invalidatedAt: new Date().toISOString() }; result.hidden = true; submit.disabled = true; highlight.disabled = true; clearHighlights.disabled = true; setStatus('当前页面已变化，旧审核结果已失效。请重新提取并审核当前岗位；历史审核记录不会被删除。'); }
async function sourceTab() { let tab = selectSourceTab(await chrome.tabs.query({ active: true, lastFocusedWindow: true })); if (!tab) { const id = (await chrome.storage.session.get('recentSourceTabId')).recentSourceTabId; if (typeof id === 'number') tab = selectSourceTab([await chrome.tabs.get(id)]); } if (!tab?.id) throw new Error('TAB_UNAVAILABLE'); return tab; }
async function restoreForCurrentTab(): Promise<void> { const saved = await loadState(); const tab = await sourceTab().catch(() => undefined); if (!saved?.binding || !tab?.id || saved.binding.tabId !== tab.id) { capture = undefined; auditResult = undefined; binding = undefined; lifecycle = { status: 'CURRENT' }; preview.hidden = true; result.hidden = true; submit.disabled = true; highlight.disabled = true; clearHighlights.disabled = true; return; } binding = saved.binding; lifecycle = saved.lifecycle; preview.hidden = true; result.hidden = true; submit.disabled = true; highlight.disabled = true; clearHighlights.disabled = true; if (saved.lifecycle.status === 'STALE') { showStale(); return; } const verified = await chrome.tabs.sendMessage(tab.id, { type: 'GET_PAGE_IDENTITY' }).catch(() => undefined) as { type?: unknown; identity?: unknown } | undefined; if (verified?.type !== 'PAGE_IDENTITY_RESOLVED' || !isPageIdentity(verified.identity) || verified.identity.captureFingerprint === null) { setStatus('正在确认当前页面身份…'); return; } const reason = invalidationReason(saved.binding, verified.identity); if (reason) { await invalidateState(reason); lifecycle = { status: 'STALE', reason, invalidatedAt: new Date().toISOString() }; showStale(); return; } if (saved.capture) showCapture(saved.capture); if (saved.result) showResult(saved.result); }
async function init() { const config = await loadConfig(); byId<HTMLInputElement>('apiBaseUrl').value = config.apiBaseUrl; byId<HTMLInputElement>('tenantId').value = config.tenantId; byId<HTMLInputElement>('accessToken').value = config.accessToken; await restoreForCurrentTab(); }
chrome.storage.onChanged.addListener((changes, area) => { if (area === 'local' && changes.jobComplianceCaptureState) void restoreForCurrentTab(); });
byId<HTMLButtonElement>('extract').addEventListener('click', async () => { setStatus('正在提取当前页面…'); try { const tab = await sourceTab(); const message = await chrome.tabs.sendMessage(tab.id!, { type: 'EXTRACT_CURRENT_JOB' }); if (typeof message !== 'object' || message === null || (message as { type?: string }).type !== 'JOB_EXTRACTION_SUCCEEDED' || !isCapture((message as { capture?: unknown }).capture)) throw new Error('NO_JOB_FOUND'); const next = (message as { capture: WebJobCapture }).capture; binding = createPageBinding(tab.id!, next); lifecycle = { status: 'CURRENT' }; auditResult = undefined; result.hidden = true; showCapture(next); await saveState({ capture: next, binding, lifecycle }); setStatus('已提取，请人工确认后提交。'); } catch (error) { setStatus(error instanceof Error && error.message === 'TAB_UNAVAILABLE' ? '未找到可提取的招聘页面。请先打开招聘岗位页面后重试。' : '未检测到可审核的岗位信息。'); } });
submit.addEventListener('click', async () => { if (sending || !current() || !binding) return; const next = updatedCapture(); if (!next || !next.job.title || !next.job.description) { setStatus('岗位名称和描述为必填项。'); return; } const requestBinding = binding; sending = true; submit.disabled = true; try { const config = { apiBaseUrl: byId<HTMLInputElement>('apiBaseUrl').value.trim(), tenantId: byId<HTMLInputElement>('tenantId').value.trim(), accessToken: byId<HTMLInputElement>('accessToken').value.trim() }; if (!config.apiBaseUrl || !config.tenantId || !config.accessToken) throw new Error('AUTH_REQUIRED'); await saveConfig(config); await saveState({ capture: next, binding: requestBinding, lifecycle: { status: 'CURRENT' } }); setStatus('正在提交审核…'); const audit = await submitAudit({ capture: next, ...config }); const latest = await loadState(); if (!latest || !acceptsAuditResponse(latest, requestBinding)) { setStatus('审核已完成，但当前页面已变化；结果未作为当前岗位展示。'); return; } await saveState({ capture: next, result: audit, binding: requestBinding, lifecycle: { status: 'CURRENT' } }); showCapture(next); showResult(audit); setStatus('审核完成。'); } catch (error) { const latest = await loadState(); if (latest?.binding?.generation === requestBinding.generation && latest.lifecycle.status === 'CURRENT') await saveState({ capture: next, binding: requestBinding, lifecycle: latest.lifecycle, error: error instanceof Error ? error.message : 'AUDIT_REQUEST_FAILED' }); setStatus(error instanceof Error && error.message === 'AUTH_REQUIRED' ? '请配置开发连接与认证。' : '提交失败，已保留修改内容，可重试。'); } finally { sending = false; if (current()) submit.disabled = false; } });
highlight.addEventListener('click', async () => { if (!auditResult || !current() || highlighting || clearing) return; const resultToHighlight = auditResult; highlighting = true; highlight.disabled = true; clearHighlights.disabled = true; setStatus('正在在页面高亮…'); try { const tab = await sourceTab(); if (tab.id !== binding?.tabId) throw new Error('PAGE_CHANGED'); const message = await chrome.tabs.sendMessage(tab.id!, { type: 'APPLY_FINDING_HIGHLIGHTS', findings: findingHighlights(resultToHighlight) }) as { type?: string; highlightedFindings?: number; unlocatedFindings?: number; }; if (message.type !== 'FINDING_HIGHLIGHTS_APPLIED') throw new Error('CONTENT_SCRIPT_UNAVAILABLE'); setStatus(`已高亮 ${message.highlightedFindings ?? 0} 项；${message.unlocatedFindings ?? 0} 项未定位。`); } catch { setStatus('无法在当前页面高亮。请保持招聘页面打开后重试。'); } finally { highlighting = false; highlight.disabled = !auditResult || !current() || findingHighlights(resultToHighlight).length === 0; clearHighlights.disabled = !current(); } });
clearHighlights.addEventListener('click', async () => { if (!current() || clearing || highlighting) return; clearing = true; highlight.disabled = true; clearHighlights.disabled = true; setStatus('正在清除页面高亮…'); try { const tab = await sourceTab(); if (tab.id !== binding?.tabId) throw new Error('PAGE_CHANGED'); const message = await chrome.tabs.sendMessage(tab.id!, { type: 'CLEAR_FINDING_HIGHLIGHTS' }) as { type?: string; clearedCount?: number; }; if (message.type !== 'FINDING_HIGHLIGHTS_CLEARED') throw new Error('CONTENT_SCRIPT_UNAVAILABLE'); setStatus(`已清除 ${message.clearedCount ?? 0} 处页面高亮。`); } catch { setStatus('无法清除当前页面高亮。请保持招聘页面打开后重试。'); } finally { clearing = false; highlight.disabled = !auditResult || !current() || findingHighlights(auditResult).length === 0; clearHighlights.disabled = !current(); } });
void init();
