import { submitAudit } from './api-client.js';
import { loadConfig,loadState,saveConfig,saveState } from './storage.js';
import type { AuditResult, WebJobCapture } from './types.js';
import { isCapture } from './types.js';
import { selectSourceTab } from './source-tab.js';

const byId=<T extends HTMLElement>(id:string)=>document.getElementById(id) as T;
const status=byId<HTMLElement>('status');const preview=byId<HTMLElement>('preview');const result=byId<HTMLElement>('result');const submit=byId<HTMLButtonElement>('submit');let capture:WebJobCapture|undefined;let sending=false;
const fields=['title','companyName','location','salary','employmentType','description','requirements'] as const;
function setStatus(value:string){status.textContent=value;}
function showCapture(value:WebJobCapture){capture=value;preview.hidden=false;submit.disabled=false;for(const field of fields){const control=document.querySelector(`[data-field="${field}"]`) as HTMLInputElement|HTMLTextAreaElement|null;if(control)control.value=field==='requirements'?value.job.requirements.join('\n'):(value.job[field as keyof typeof value.job] as string|undefined??'');}byId<HTMLElement>('warnings').textContent=value.extractionWarnings.join('\n');}
function updatedCapture():WebJobCapture|undefined{if(!capture)return undefined;const job={...capture.job};for(const field of fields){const control=document.querySelector(`[data-field="${field}"]`) as HTMLInputElement|HTMLTextAreaElement|null;const value=control?.value.trim()??'';if(field==='requirements')job.requirements=value?value.split('\n').map(x=>x.trim()).filter(Boolean):[];else if(field==='title'||field==='description')job[field]=value;else if(value)job[field as keyof typeof job]=value as never;else delete job[field as keyof typeof job];}return {...capture,job,userCorrected:true};}
function showResult(value:AuditResult){result.hidden=false;byId<HTMLElement>('decision').textContent=`${value.decision} · ${value.riskLevel}`;byId<HTMLElement>('summary').textContent=value.summary;byId<HTMLElement>('auditId').textContent=`AuditRun: ${value.auditId} · ${value.createdAt}`;const list=byId<HTMLUListElement>('findings');list.replaceChildren();for(const finding of value.findings){const item=document.createElement('li');const matched=(finding.metadata?.matchedText?.join('、')??finding.evidence.flatMap(e=>e.quote?[e.quote]:[]).join('、'))||'未提供原文';item.textContent=`[${finding.severity}] ${finding.category}：${matched}。${finding.message}`;list.append(item);}}
async function init(){const config=await loadConfig();byId<HTMLInputElement>('apiBaseUrl').value=config.apiBaseUrl;byId<HTMLInputElement>('tenantId').value=config.tenantId;byId<HTMLInputElement>('accessToken').value=config.accessToken;const saved=await loadState();if(saved?.capture)showCapture(saved.capture);if(saved?.result)showResult(saved.result);}
byId<HTMLButtonElement>('extract').addEventListener('click',async()=>{setStatus('正在提取当前页面…');try{let tab=selectSourceTab(await chrome.tabs.query({active:true,lastFocusedWindow:true}));if(!tab){const id=(await chrome.storage.session.get('recentSourceTabId')).recentSourceTabId;if(typeof id==='number')tab=selectSourceTab([await chrome.tabs.get(id)]);}if(!tab?.id)throw new Error('TAB_UNAVAILABLE');const message=await chrome.tabs.sendMessage(tab.id,{type:'EXTRACT_CURRENT_JOB'});if(typeof message!=='object'||message===null||(message as {type?:string}).type!=='JOB_EXTRACTION_SUCCEEDED'||!isCapture((message as {capture?:unknown}).capture))throw new Error('NO_JOB_FOUND');showCapture((message as {capture:WebJobCapture}).capture);await saveState({capture:(message as {capture:WebJobCapture}).capture});setStatus('已提取，请人工确认后提交。');}catch(error){setStatus(error instanceof Error&&error.message==='TAB_UNAVAILABLE'?'未找到可提取的招聘页面。请先打开招聘岗位页面后重试。':'未检测到可审核的岗位信息。');}});
submit.addEventListener('click',async()=>{if(sending)return;const next=updatedCapture();if(!next||!next.job.title||!next.job.description){setStatus('岗位名称和描述为必填项。');return;}sending=true;submit.disabled=true;try{const config={apiBaseUrl:byId<HTMLInputElement>('apiBaseUrl').value.trim(),tenantId:byId<HTMLInputElement>('tenantId').value.trim(),accessToken:byId<HTMLInputElement>('accessToken').value.trim()};if(!config.apiBaseUrl||!config.tenantId||!config.accessToken)throw new Error('AUTH_REQUIRED');await saveConfig(config);await saveState({capture:next});setStatus('正在提交审核…');const audit=await submitAudit({capture:next,...config});await saveState({capture:next,result:audit});showCapture(next);showResult(audit);setStatus('审核完成。');}catch(error){await saveState({capture:next,error:error instanceof Error?error.message:'AUDIT_REQUEST_FAILED'});setStatus(error instanceof Error&&error.message==='AUTH_REQUIRED'?'请配置开发连接与认证。':'提交失败，已保留修改内容，可重试。');}finally{sending=false;submit.disabled=false;}});void init();
