import type { FastifyInstance, FastifyRequest } from 'fastify';
import { z } from 'zod';
import type { AuthServices } from '../auth/service.js';
import type { LLMSettingsService } from './service.js';
const id = z.object({ id: z.string().uuid() }); const tenant = z.object({ tenantId: z.string().min(1) });
const create = z.object({ tenantId: z.string().min(1), displayName: z.string().min(1), provider: z.enum(['OPENAI','OPENAI_COMPATIBLE','LOCAL_OPENAI_COMPATIBLE']), baseUrl: z.string().url().optional(), apiKey: z.string().min(8), auditModel: z.string().min(1), timeoutMs: z.number().int().min(100).max(60000).default(8000), maxOutputTokens: z.number().int().min(1).max(32000).default(1024), temperature: z.number().min(0).max(2).default(0), maxRetries: z.number().int().min(0).max(3).default(1), isDefault: z.boolean().default(false) });
const update = create.omit({ tenantId: true, provider: true }).partial();
export function registerSettingsRoutes(app: FastifyInstance, service: LLMSettingsService, auth: AuthServices): void {
  const writable = (request: FastifyRequest, tenantId: string) => { auth.authService.requirePermission(request, 'settings:write'); auth.authService.requireTenantAccess(request, tenantId); };
  app.get('/api/settings/llm-connections', async (request, reply) => { const q = tenant.parse(request.query); auth.authService.requirePermission(request, 'settings:read'); auth.authService.requireTenantAccess(request, q.tenantId); return reply.send({ items: service.list(q.tenantId) }); });
  app.get('/api/settings/llm-connections/:id', async (request, reply) => { const p=id.parse(request.params), q=tenant.parse(request.query); auth.authService.requirePermission(request, 'settings:read'); auth.authService.requireTenantAccess(request,q.tenantId); const item=service.get(p.id,q.tenantId); return item ? reply.send(service.list(q.tenantId).find((connection) => connection.id === item.id)) : reply.code(404).send({ error: { code: 'LLM_CONNECTION_NOT_FOUND', message: 'Connection was not found.', retryable: false } }); });
  app.post('/api/settings/llm-connections', async (request, reply) => { const body = create.parse(request.body); writable(request, body.tenantId); const actor = auth.authService.getContext(request); const item = await service.create({ ...body, ...(body.baseUrl === undefined ? {} : { baseUrl: body.baseUrl }), createdBy: actor.userId }); auth.auditLogService.record({ actor, tenantId: body.tenantId, operation: 'llm_connection.create', resourceType: 'llm_connection', resourceId: item.id, after: item, requestId: request.id }); return reply.code(201).send(item); });
  app.patch('/api/settings/llm-connections/:id', async (request, reply) => { const p = id.parse(request.params), q = tenant.parse(request.query), body = update.parse(request.body); writable(request, q.tenantId); const item = await service.update(p.id,q.tenantId, Object.fromEntries(Object.entries(body).filter(([, value]) => value !== undefined))); return item ? reply.send(item) : reply.code(404).send({ error: { code: 'LLM_CONNECTION_NOT_FOUND', message: 'Connection was not found.', retryable: false } }); });
  app.delete('/api/settings/llm-connections/:id', async (request, reply) => { const p=id.parse(request.params), q=tenant.parse(request.query); writable(request,q.tenantId); return reply.code(service.delete(p.id,q.tenantId) ? 204 : 404).send(); });
  for (const action of ['verify','set-default','disable','rotate-key'] as const) app.post(`/api/settings/llm-connections/:id/${action}`, async (request, reply) => { const p=id.parse(request.params), q=tenant.parse(request.query); writable(request,q.tenantId); const item = action === 'verify' ? service.verify(p.id,q.tenantId) : action === 'set-default' ? service.setDefault(p.id,q.tenantId) : action === 'disable' ? service.disable(p.id,q.tenantId) : await service.rotate(p.id,q.tenantId); return item ? reply.send(action === 'verify' ? { success: true, connection: item, capabilities: { structuredOutput: true, reasoningEffort: false, streaming: false, embeddings: false } } : item) : reply.code(404).send({ error: { code: 'LLM_CONNECTION_NOT_FOUND', message: 'Connection was not found or is not verified.', retryable: false } }); });
  app.get('/api/settings/llm-routing', async (request, reply) => { const q=tenant.parse(request.query); auth.authService.requirePermission(request,'settings:read'); auth.authService.requireTenantAccess(request,q.tenantId); return reply.send(service.policy(q.tenantId)); });
  app.patch('/api/settings/llm-routing', async (request, reply) => { const q=tenant.parse(request.query); writable(request,q.tenantId); return reply.send(service.updatePolicy(q.tenantId, Object.fromEntries(Object.entries(z.object({ classifierLowConfidenceThreshold:z.number().min(0).max(1).optional(), classifierHighConfidenceThreshold:z.number().min(0).max(1).optional(), fastLLMEnabled:z.boolean().optional(), deepReviewEnabled:z.boolean().optional(), skipLLMWhenRuleDecisionIsDeterministic:z.boolean().optional() }).parse(request.body)).filter(([, value]) => value !== undefined)))); });
}
