import { randomUUID } from 'node:crypto';
import type { EncryptedSecret } from '@job-compliance/core';
import pg from 'pg';

export type ConnectionStatus = 'ACTIVE' | 'DISABLED' | 'INVALID' | 'RATE_LIMITED' | 'DEGRADED' | 'UNAVAILABLE' | 'UNVERIFIED';
export interface LLMConnectionEntity { id: string; tenantId: string; displayName: string; provider: string; baseUrl?: string; encryptedApiKey: EncryptedSecret; apiKeyLastFour?: string; auditModel: string; timeoutMs: number; maxOutputTokens: number; temperature: number; maxRetries: number; status: ConnectionStatus; isDefault: boolean; createdBy: string; createdAt: string; updatedAt: string; }
export interface RoutingPolicyEntity { tenantId: string; version: string; enabled: boolean; [key: string]: unknown; }
export interface LLMUsageEntity { id: string; tenantId: string; auditRunId?: string; asyncJobId?: string; connectionId?: string; provider: string; model: string; taskType?: string; promptVersion?: string; inputTokens?: number; outputTokens?: number; cachedTokens?: number; durationMs?: number; success?: boolean; errorCode?: string; retryCount: number; estimatedCost?: number; currency?: string; pricingVersion?: string; isMock: boolean; createdAt: string; }
export interface AsyncJobEntity { id: string; tenantId: string; type: string; status: string; auditRunId?: string; payload: Record<string, unknown>; result?: unknown; attemptCount: number; maxAttempts: number; idempotencyKey?: string; }

const defaultPolicy = (tenantId: string): RoutingPolicyEntity => ({ tenantId, version: 'routing-v1', enabled: true, skipLLMWhenRuleDecisionIsDeterministic: true, classifierEnabled: true, classifierLowConfidenceThreshold: .35, classifierHighConfidenceThreshold: .85, fastLLMEnabled: true, fastLLMMaxInputChars: 12000, fastLLMTimeoutMs: 8000, deepReviewEnabled: false, timeoutFallback: 'MANUAL_REVIEW', providerErrorFallback: 'MANUAL_REVIEW', invalidOutputFallback: 'RETRY_ONCE' });
const iso = (value: Date | string) => new Date(value).toISOString();
const connection = (row: Record<string, unknown>): LLMConnectionEntity => ({ id: String(row.id), tenantId: String(row.tenant_id), displayName: String(row.display_name), provider: String(row.provider), ...(row.base_url ? { baseUrl: String(row.base_url) } : {}), encryptedApiKey: row.encrypted_api_key as EncryptedSecret, ...(row.api_key_last_four ? { apiKeyLastFour: String(row.api_key_last_four) } : {}), auditModel: String(row.audit_model), timeoutMs: Number(row.timeout_ms), maxOutputTokens: Number(row.max_output_tokens), temperature: Number(row.temperature), maxRetries: Number(row.max_retries), status: String(row.status) as ConnectionStatus, isDefault: Boolean(row.is_default), createdBy: String(row.created_by), createdAt: iso(row.created_at as Date), updatedAt: iso(row.updated_at as Date) });

/** PostgreSQL-only persistence adapter. It never falls back to an in-process store. */
export class PostgresLLMPersistenceRepository {
  readonly pool: pg.Pool;
  constructor(connectionString = process.env.DATABASE_URL, pool?: pg.Pool) { if (!pool && !connectionString) throw new Error('DATABASE_URL is required for PostgreSQL LLM persistence.'); this.pool = pool ?? new pg.Pool({ connectionString }); }
  async close(): Promise<void> { await this.pool.end(); }
  async createConnection(input: Omit<LLMConnectionEntity, 'id'|'createdAt'|'updatedAt'>): Promise<LLMConnectionEntity> { const id=randomUUID(); const client=await this.pool.connect(); try { await client.query('BEGIN'); if (input.isDefault) await client.query("UPDATE llm_connections SET is_default=false, updated_at=NOW() WHERE tenant_id=$1 AND is_default=true", [input.tenantId]); const r=await client.query(`INSERT INTO llm_connections (id,tenant_id,display_name,provider,base_url,encrypted_api_key,api_key_last_four,audit_model,timeout_ms,max_output_tokens,temperature,max_retries,status,is_default,created_by) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING *`, [id,input.tenantId,input.displayName,input.provider,input.baseUrl??null,JSON.stringify(input.encryptedApiKey),input.apiKeyLastFour??null,input.auditModel,input.timeoutMs,input.maxOutputTokens,input.temperature,input.maxRetries,input.status,input.isDefault,input.createdBy]); await client.query('COMMIT'); return connection(r.rows[0] as Record<string,unknown>); } catch(e) { await client.query('ROLLBACK'); throw e; } finally { client.release(); } }
  async listByTenant(tenantId: string): Promise<LLMConnectionEntity[]> { const r=await this.pool.query('SELECT * FROM llm_connections WHERE tenant_id=$1 ORDER BY created_at DESC',[tenantId]); return r.rows.map(x=>connection(x)); }
  async findById(tenantId: string,id: string): Promise<LLMConnectionEntity|null> { const r=await this.pool.query('SELECT * FROM llm_connections WHERE tenant_id=$1 AND id=$2',[tenantId,id]); return r.rowCount ? connection(r.rows[0]) : null; }
  async findDefault(tenantId:string):Promise<LLMConnectionEntity|null>{const r=await this.pool.query("SELECT * FROM llm_connections WHERE tenant_id=$1 AND is_default=true AND status='ACTIVE'",[tenantId]);return r.rowCount?connection(r.rows[0]):null;}
  async updateConnection(tenantId:string,id:string, patch:Partial<Pick<LLMConnectionEntity,'displayName'|'baseUrl'|'auditModel'|'timeoutMs'|'maxOutputTokens'|'temperature'|'maxRetries'>>): Promise<LLMConnectionEntity|null> { const current=await this.findById(tenantId,id); if(!current) return null; const n={...current,...patch}; const r=await this.pool.query('UPDATE llm_connections SET display_name=$3,base_url=$4,audit_model=$5,timeout_ms=$6,max_output_tokens=$7,temperature=$8,max_retries=$9,updated_at=NOW() WHERE tenant_id=$1 AND id=$2 RETURNING *',[tenantId,id,n.displayName,n.baseUrl??null,n.auditModel,n.timeoutMs,n.maxOutputTokens,n.temperature,n.maxRetries]); return connection(r.rows[0]); }
  async updateSecret(tenantId:string,id:string,secret:EncryptedSecret,lastFour?:string):Promise<boolean>{ const r=await this.pool.query('UPDATE llm_connections SET encrypted_api_key=$3,api_key_last_four=$4,updated_at=NOW() WHERE tenant_id=$1 AND id=$2',[tenantId,id,JSON.stringify(secret),lastFour??null]); return r.rowCount===1; }
  async setDefault(tenantId:string,id:string):Promise<LLMConnectionEntity|null>{ const c=await this.pool.connect(); try { await c.query('BEGIN'); const selected=await c.query("SELECT * FROM llm_connections WHERE tenant_id=$1 AND id=$2 AND status='ACTIVE' FOR UPDATE",[tenantId,id]); if(!selected.rowCount){await c.query('ROLLBACK');return null;} await c.query('UPDATE llm_connections SET is_default=false,updated_at=NOW() WHERE tenant_id=$1 AND is_default=true',[tenantId]); const r=await c.query('UPDATE llm_connections SET is_default=true,updated_at=NOW() WHERE tenant_id=$1 AND id=$2 RETURNING *',[tenantId,id]); await c.query('COMMIT'); return connection(r.rows[0]); }catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();} }
  async setStatus(tenantId:string,id:string,status:ConnectionStatus):Promise<LLMConnectionEntity|null>{ const r=await this.pool.query('UPDATE llm_connections SET status=$3,is_default=CASE WHEN $3=\'DISABLED\' THEN false ELSE is_default END,updated_at=NOW() WHERE tenant_id=$1 AND id=$2 RETURNING *',[tenantId,id,status]);return r.rowCount?connection(r.rows[0]):null; }
  async recordVerification(tenantId:string,id:string,input:{status:ConnectionStatus;errorCode?:string;success:boolean}):Promise<LLMConnectionEntity|null>{const r=await this.pool.query(`UPDATE llm_connections SET status=$3,last_verified_at=NOW(),last_success_at=CASE WHEN $4 THEN NOW() ELSE last_success_at END,last_failure_at=CASE WHEN $4 THEN last_failure_at ELSE NOW() END,last_error_code=$5,updated_at=NOW() WHERE tenant_id=$1 AND id=$2 RETURNING *`,[tenantId,id,input.status,input.success,input.errorCode??null]);return r.rowCount?connection(r.rows[0]):null;}
  async deleteConnection(tenantId:string,id:string):Promise<boolean>{return (await this.pool.query('DELETE FROM llm_connections WHERE tenant_id=$1 AND id=$2',[tenantId,id])).rowCount===1;}
  async getCurrentPolicy(tenantId:string):Promise<RoutingPolicyEntity>{const existing=await this.pool.query('SELECT version,enabled,payload FROM audit_routing_policies WHERE tenant_id=$1',[tenantId]);if(existing.rowCount)return {tenantId,version:existing.rows[0].version,enabled:existing.rows[0].enabled,...existing.rows[0].payload};return this.createDefaultPolicy(tenantId);}
  async createDefaultPolicy(tenantId:string):Promise<RoutingPolicyEntity>{const p=defaultPolicy(tenantId); const id=randomUUID(); await this.pool.query('INSERT INTO audit_routing_policies(id,tenant_id,version,enabled,payload) VALUES($1,$2,$3,$4,$5) ON CONFLICT(tenant_id) DO NOTHING',[id,tenantId,p.version,p.enabled,JSON.stringify(p)]); await this.pool.query('INSERT INTO audit_routing_policy_versions(id,tenant_id,version,enabled,payload,created_by) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(tenant_id,version) DO NOTHING',[randomUUID(),tenantId,p.version,p.enabled,JSON.stringify(p),'system']); return this.getCurrentPolicyRead(tenantId);}
  private async getCurrentPolicyRead(tenantId:string):Promise<RoutingPolicyEntity>{const r=await this.pool.query('SELECT version,enabled,payload FROM audit_routing_policies WHERE tenant_id=$1',[tenantId]);return {tenantId,version:r.rows[0].version,enabled:r.rows[0].enabled,...r.rows[0].payload};}
  async updatePolicy(tenantId:string,patch:Record<string,unknown>,updatedBy:string):Promise<RoutingPolicyEntity>{const c=await this.pool.connect();try{await c.query('BEGIN');const current=await this.getCurrentPolicy(tenantId);const p: RoutingPolicyEntity={...current,...patch,version:`routing-${Date.now()}`};if(Number(p['classifierLowConfidenceThreshold'])>=Number(p['classifierHighConfidenceThreshold']))throw new Error('Classifier low threshold must be below high threshold.');await c.query('UPDATE audit_routing_policies SET version=$2,enabled=$3,payload=$4,updated_at=NOW() WHERE tenant_id=$1',[tenantId,p.version,p.enabled,JSON.stringify(p)]);await c.query('INSERT INTO audit_routing_policy_versions(id,tenant_id,version,enabled,payload,created_by) VALUES($1,$2,$3,$4,$5,$6)',[randomUUID(),tenantId,p.version,p.enabled,JSON.stringify(p),updatedBy]);await c.query('COMMIT');return p;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
  async listPolicyVersions(tenantId:string):Promise<RoutingPolicyEntity[]>{const r=await this.pool.query('SELECT version,enabled,payload FROM audit_routing_policy_versions WHERE tenant_id=$1 ORDER BY created_at DESC',[tenantId]);return r.rows.map(x=>({tenantId,version:x.version,enabled:x.enabled,...x.payload}));}
  async restorePolicy(tenantId:string,version:string,updatedBy:string):Promise<RoutingPolicyEntity>{const r=await this.pool.query('SELECT payload FROM audit_routing_policy_versions WHERE tenant_id=$1 AND version=$2',[tenantId,version]);if(!r.rowCount)throw new Error('Routing policy version was not found.');const {version:_ignored,...payload}=r.rows[0].payload as Record<string,unknown>;return this.updatePolicy(tenantId,payload,updatedBy);}
  async saveTrace(tenantId:string,auditRunId:string,trace:Record<string,unknown>):Promise<void>{await this.pool.query('INSERT INTO audit_routing_traces(id,tenant_id,audit_run_id,trace) VALUES($1,$2,$3,$4) ON CONFLICT(tenant_id,audit_run_id) DO UPDATE SET trace=EXCLUDED.trace,updated_at=NOW()',[randomUUID(),tenantId,auditRunId,JSON.stringify(trace)]);}
  async findTrace(tenantId:string,auditRunId:string):Promise<Record<string,unknown>|null>{const r=await this.pool.query('SELECT trace FROM audit_routing_traces WHERE tenant_id=$1 AND audit_run_id=$2',[tenantId,auditRunId]);return r.rowCount?r.rows[0].trace:null;}
  async createUsage(input:Omit<LLMUsageEntity,'id'|'createdAt'|'retryCount'> & {retryCount?:number}):Promise<LLMUsageEntity>{const id=randomUUID();const r=await this.pool.query(`INSERT INTO llm_usage_records(id,tenant_id,audit_run_id,async_job_id,connection_id,provider,model,task_type,prompt_version,input_tokens,output_tokens,cached_tokens,duration_ms,success,error_code,retry_count,estimated_cost,currency,pricing_version,is_mock,tokens_in,tokens_out,cost,status,payload) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,0,0,0,$21,$22) RETURNING created_at`,[id,input.tenantId,input.auditRunId??null,input.asyncJobId??null,input.connectionId??null,input.provider,input.model,input.taskType??null,input.promptVersion??null,input.inputTokens??null,input.outputTokens??null,input.cachedTokens??null,input.durationMs??null,input.success??null,input.errorCode??null,input.retryCount??0,input.estimatedCost??null,input.currency??null,input.pricingVersion??null,input.isMock,input.success===false?'FAILED':'COMPLETED','{}']);return {...input,id,retryCount:input.retryCount??0,createdAt:iso(r.rows[0].created_at)};}
  async listUsage(tenantId:string,auditRunId:string):Promise<LLMUsageEntity[]>{const r=await this.pool.query('SELECT * FROM llm_usage_records WHERE tenant_id=$1 AND audit_run_id=$2 ORDER BY created_at',[tenantId,auditRunId]);return r.rows.map(x=>({id:x.id,tenantId:x.tenant_id,auditRunId:x.audit_run_id??undefined,asyncJobId:x.async_job_id??undefined,connectionId:x.connection_id??undefined,provider:x.provider,model:x.model,taskType:x.task_type??undefined,promptVersion:x.prompt_version??undefined,inputTokens:x.input_tokens??undefined,outputTokens:x.output_tokens??undefined,cachedTokens:x.cached_tokens??undefined,durationMs:x.duration_ms??undefined,success:x.success??undefined,errorCode:x.error_code??undefined,retryCount:x.retry_count,isMock:x.is_mock,createdAt:iso(x.created_at)}));}
  async enqueue(input:{tenantId:string;type:string;auditRunId?:string;payload:Record<string,unknown>;idempotencyKey:string;maxAttempts?:number}):Promise<AsyncJobEntity>{const id=randomUUID();const r=await this.pool.query(`INSERT INTO async_jobs(id,type,tenant_id,status,audit_run_id,payload,idempotency_key,max_attempts) VALUES($1,$2,$3,'PENDING',$4,$5,$6,$7) ON CONFLICT(tenant_id,idempotency_key) WHERE idempotency_key IS NOT NULL DO UPDATE SET updated_at=NOW() RETURNING *`,[id,input.type,input.tenantId,input.auditRunId??null,JSON.stringify(input.payload),input.idempotencyKey,input.maxAttempts??3]);const x=r.rows[0];return {id:x.id,tenantId:x.tenant_id,type:x.type,status:x.status,auditRunId:x.audit_run_id??undefined,payload:x.payload,attemptCount:x.attempt_count,maxAttempts:x.max_attempts,idempotencyKey:x.idempotency_key};}
  async claimNext(workerId:string,types:string[],lockDurationMs:number):Promise<AsyncJobEntity|null>{const r=await this.pool.query(`WITH candidate AS (SELECT id FROM async_jobs WHERE type=ANY($1) AND status IN ('PENDING','RETRY_WAIT') AND available_at<=NOW() ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 1) UPDATE async_jobs j SET status='RUNNING',locked_by=$2,locked_at=NOW(),lock_expires_at=NOW()+($3::text||' milliseconds')::interval,attempt_count=attempt_count+1,started_at=COALESCE(started_at,NOW()),updated_at=NOW() FROM candidate WHERE j.id=candidate.id RETURNING j.*`,[types,workerId,lockDurationMs]);if(!r.rowCount)return null;const x=r.rows[0];return{id:x.id,tenantId:x.tenant_id,type:x.type,status:x.status,auditRunId:x.audit_run_id??undefined,payload:x.payload,attemptCount:x.attempt_count,maxAttempts:x.max_attempts,idempotencyKey:x.idempotency_key};}
  async completeJob(id:string,result:unknown):Promise<void>{await this.pool.query("UPDATE async_jobs SET status='COMPLETED',result=$2,completed_at=NOW(),locked_by=NULL,locked_at=NULL,lock_expires_at=NULL,updated_at=NOW() WHERE id=$1",[id,JSON.stringify(result)]);}
  async retryJob(id:string,errorCode:string,availableAt:Date):Promise<void>{await this.pool.query("UPDATE async_jobs SET status='RETRY_WAIT',last_error_code=$2,available_at=$3,locked_by=NULL,locked_at=NULL,lock_expires_at=NULL,updated_at=NOW() WHERE id=$1",[id,errorCode,availableAt]);}
  async deadLetter(id:string,errorCode:string):Promise<void>{await this.pool.query("UPDATE async_jobs SET status='DEAD_LETTER',last_error_code=$2,locked_by=NULL,locked_at=NULL,lock_expires_at=NULL,completed_at=NOW(),updated_at=NOW() WHERE id=$1",[id,errorCode]);}
  async releaseExpiredLocks():Promise<number>{const r=await this.pool.query("UPDATE async_jobs SET status='RETRY_WAIT',locked_by=NULL,locked_at=NULL,lock_expires_at=NULL,available_at=NOW(),updated_at=NOW() WHERE status='RUNNING' AND lock_expires_at<NOW()");return r.rowCount??0;}
  async saveEnrichment(input:{tenantId:string;auditRunId:string;taskType:string;status:string;result?:unknown;safetyResult?:unknown;errorCode?:string;promptVersion?:string;provider?:string;model?:string;isMock:boolean}):Promise<void>{const r=await this.pool.query('SELECT COALESCE(MAX(version),0)+1 AS version FROM audit_enrichment_records WHERE tenant_id=$1 AND audit_run_id=$2 AND task_type=$3',[input.tenantId,input.auditRunId,input.taskType]);await this.pool.query('INSERT INTO audit_enrichment_records(id,tenant_id,audit_run_id,task_type,version,status,result,safety_result,error_code,prompt_version,provider,model,is_mock) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)',[randomUUID(),input.tenantId,input.auditRunId,input.taskType,r.rows[0].version,input.status,input.result===undefined?null:JSON.stringify(input.result),input.safetyResult===undefined?null:JSON.stringify(input.safetyResult),input.errorCode??null,input.promptVersion??null,input.provider??null,input.model??null,input.isMock]);}
  async listEnrichment(tenantId:string,auditRunId:string):Promise<Record<string,unknown>[]>{const r=await this.pool.query('SELECT task_type,status,result,safety_result,error_code,prompt_version,provider,model,is_mock,created_at,updated_at FROM audit_enrichment_records WHERE tenant_id=$1 AND audit_run_id=$2 ORDER BY task_type,version DESC',[tenantId,auditRunId]);return r.rows;}
}
